### ISSUE TITLE
Warning: Legacy context API has been detected within a strict-mode tree.

### ISSUE THREAD

**Issue by ahmsalah** [oliviertassinari/react-swipeable-views#596]
Warning: Legacy context API has been detected within a strict-mode tree.

The old API will be supported in all 16.x releases, but applications using it should migrate to the new version.

Please update the following components: ReactSwipableView

Learn more about this warning here: https://fb.me/react-legacy-context
    in ReactSwipableView

- [x] I have searched the [issues](https://github.com/oliviertassinari/react-swipeable-views/issues) of this repository and believe that this is not a duplicate.

| Tech                   | Version |
|------------------------|---------|
| react-swipeable-views  | 0.13.9 |
| React                  | 16.13.1  |
| platform               |     Win 10    |
| etc                    |         |

**Comment by artmxra7** [comment]
same Problem

**Comment by robinduckett** [comment]
I also get the following error, is this related?

```
Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: ReactSwipableView
```

**Comment by matthewkwong2** [comment]
> I also get the following error, is this related?
> 
> ```
> Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.
> 
> * Move data fetching code or side effects to componentDidUpdate.
> * If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
> * Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
> 
> Please update the following components: ReactSwipableView
> ```

Not exactly, but similar. Basically, this error means ` ReactSwipableView` is using the deprecated `componentWillReceiveProps`  life cycle function. The error in the original post means `ReactSwipableView` is using the old deprecated context API.

**Comment by LordLalwani** [comment]
Any updates regarding this? 🤔

**Comment by MaxSvargal** [comment]
Oh, let's go to fix it by ourselves.

**Comment by AlbertCarreras** [comment]
Hey I put PR to remove legacy context from SwipeableWiews: https://github.com/oliviertassinari/react-swipeable-views/pull/631

The same pattern can be used in other components.

Re, UNSAFE_ I removed from SwipeableWiews as well: https://github.com/oliviertassinari/react-swipeable-views/pull/630

**Comment by pablougas** [comment]
Is anyone planning on fixing this annoying alert/error? Let us know, I'm sure one of us would be happy to jump in and update the code.

**Comment by chrisschaub** [comment]
Can this get merged in?

**Comment by lorandnagy97** [comment]
@chrisschaub
You can try use:

`npm install --save AlbertCarreras/react-swipeable-views.git#6d86cf12`

**Comment by lorandnagy97** [comment]
@chrisschaub
I agree it should be merged in, in the meantime you can install directly from the branch
https://stackoverflow.com/questions/39732397/install-specific-branch-from-github-using-npm

**Comment by prineshaz** [comment]
Can this be merged in please?

**Comment by Shezman** [comment]
When will this be merged?

**Comment by Gurkengewuerz** [comment]
Hmmm no updates?

**Comment by KirianCaumes** [comment]
Would be awesome to have an update on this one 😁
Thanks in advance

**Comment by KirianCaumes** [comment]
If anyone could tell me if it's possible to install the fork of @AlbertCarreras like @lorandnagy97 mentioned, that would be great too! Because so far I have not managed to make it work. 😕

**Comment by SOTL** [comment]
Any updaters? 🙏

**Comment by andrewtremblay** [comment]
There is a PR with approval from @oliviertassinari but the author of the PR does not have permission to merge into the repository https://github.com/oliviertassinari/react-swipeable-views/pull/645

**Comment by oliviertassinari** [comment]
A reproduction of the issue: https://codesandbox.io/s/material-demo-forked-n6rvl?file=/index.js.

**Comment by oliviertassinari** [comment]
Fixed https://codesandbox.io/s/material-demo-forked-y9s5u?file=/package.json in v0.14.0

**Comment by matthewkwong2** [comment]
> Fixed https://codesandbox.io/s/material-demo-forked-y9s5u?file=/package.json in v0.14.0

Are you referring to the Context API? Because I'm still seeing warnings for `UNSAFE_componentWillReceiveProps`. I guess that's the next thing we should work on.

**Comment by oliviertassinari** [comment]
> Are you referring to the Context API?

@matthewkwong2 Yes. 

<img width="523" alt="Capture d’écran 2021-05-31 à 22 59 49" src="https://user-images.githubusercontent.com/3165635/120241858-ec7b8180-c263-11eb-8175-920aea8b5466.png">

> I'm still seeing warnings for UNSAFE_componentWillReceiveProps. I guess that's the next thing we should work on.

Correct

**Comment by power-f-GOD** [comment]
Hi. Any updates on this so far?
